version: '3'
services:
    grafana:
        container_name: grafana
        image: grafana/grafana
        ports:
            - '53000:3000'
        volumes:
            - grafana-storage:/var/lib/grafana
        links:
            - influxdb
    influxdb:
        container_name: influxdb
        image: influxdb:latest
        environment:
          - INFLUXDB_DB=telegraf 
          - INFLUXDB_ADMIN_ENABLED=true
          - INFLUXDB_ADMIN_USER=admin
          - INFLUXDB_ADMIN_PASSWORD=iwjaja
          - INFLUXDB_USER=telegraf 
          - INFLUXDB_USER_PASSWORD=iwjaja
        ports:
            - "58083:8083"
            - "58086:8086"
        volumes:
            - influxdb-storage:/var/lib/influxdb
    telegraf:
        container_name: telegraf
        image: telegraf:1.12.3
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/host/proc
              #- ${PWD}/conf/telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
volumes:
    influxdb-storage:
    grafana-storage:

